SEARCH_AUTO_SCREENING_DATA=
SELECT LOAN_APPLI_ID
FROM
  WF_ACTIVE_FLOW_NODE
  INNER JOIN LOAN_APPLICATION
    ON INSTANCE_ID = WF_INSTANCE_ID
WHERE FLOW_NODE_ID = 'AUTO_SCREENING'

GET_LOAN_APPLICATION_WITH_LOCK =
SELECT *
FROM LOAN_APPLICATION
WHERE LOAN_APPLI_ID = ?
FOR UPDATE 

LOCK =
SELECT *
FROM LOAN_APPLICATION
WHERE LOAN_APPLI_ID = :loanAppliId
AND VERSION = :version
FOR UPDATE 


