USERS_BY_GROUP =
SELECT
    USERS.USER_ID,
    USERS.KANJI_NAME
FROM
    USERS
INNER JOIN
    UGROUP_SYSTEM_ACCOUNT
ON
    USERS.USER_ID = UGROUP_SYSTEM_ACCOUNT.USER_ID
WHERE
    UGROUP_SYSTEM_ACCOUNT.UGROUP_ID = ?
ORDER BY
    USERS.USER_ID
