CREATE SEQUENCE if not exists WF_INSTANCE_ID;
CREATE SEQUENCE if not exists TRANS_EXPE_APPLI_ID;
CREATE SEQUENCE if not exists LOAN_APPLI_ID;
CREATE SEQUENCE if not exists TRANS_EXPE_APPLI_HISTORY_ID;
CREATE SEQUENCE if not exists LOAN_APPLI_HISTORY_ID;
