DROP TABLE WF_ACTIVE_FLOW_NODE
;
DROP TABLE WF_ACTIVE_GROUP_TASK
;
DROP TABLE WF_ACTIVE_USER_TASK
;
DROP TABLE WF_BOUNDARY_EVENT
;
DROP TABLE WF_BOUNDARY_EVENT_TRIGGER
;
DROP TABLE WF_EVENT
;
DROP TABLE WF_FLOW_NODE
;
DROP TABLE WF_GATEWAY
;
DROP TABLE WF_INSTANCE
;
DROP TABLE WF_INSTANCE_FLOW_NODE
;
DROP TABLE WF_LANE
;
DROP TABLE WF_SEQUENCE_FLOW
;
DROP TABLE WF_TASK
;
DROP TABLE WF_TASK_ASSIGNED_GROUP
;
DROP TABLE WF_TASK_ASSIGNED_USER
;
DROP TABLE WF_WORKFLOW_DEFINITION
;