--- 認可に関する制約
ALTER TABLE USERS
    ADD(CONSTRAINT FK_SYSTEM_ACCOUNT_USERS FOREIGN KEY(USER_ID) REFERENCES SYSTEM_ACCOUNT (USER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE PERMISSION_UNIT_REQUEST
    ADD(CONSTRAINT FK_REQUEST_PERMISSION_UNIT_REQ FOREIGN KEY(REQUEST_ID) REFERENCES REQUEST (REQUEST_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE PERMISSION_UNIT_REQUEST
    ADD(CONSTRAINT FK_PERMISSION_UNIT_PERMISSION_ FOREIGN KEY(PERMISSION_UNIT_ID) REFERENCES PERMISSION_UNIT (PERMISSION_UNIT_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE SYSTEM_ACCOUNT_AUTHORITY
    ADD(CONSTRAINT FK_PERMISSION_UNIT_SYSTEM_ACCO FOREIGN KEY(PERMISSION_UNIT_ID) REFERENCES PERMISSION_UNIT (PERMISSION_UNIT_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE UGROUP_AUTHORITY
    ADD(CONSTRAINT FK_PERMISSION_UNIT_UGROUP_AUTH FOREIGN KEY(PERMISSION_UNIT_ID) REFERENCES PERMISSION_UNIT (PERMISSION_UNIT_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE SYSTEM_ACCOUNT_AUTHORITY
    ADD(CONSTRAINT FK_SYSTEM_ACCOUNT_SYSTEM_ACCOU FOREIGN KEY(USER_ID) REFERENCES SYSTEM_ACCOUNT (USER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE UGROUP_AUTHORITY
    ADD(CONSTRAINT FK_UGROUP_UGROUP_AUTHORITY FOREIGN KEY(UGROUP_ID) REFERENCES UGROUP (UGROUP_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE UGROUP_SYSTEM_ACCOUNT
    ADD(CONSTRAINT FK_SYSTEM_ACCOUNT_UGROUP_SYSTE FOREIGN KEY(USER_ID) REFERENCES SYSTEM_ACCOUNT (USER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE UGROUP_SYSTEM_ACCOUNT
    ADD(CONSTRAINT FK_UGROUP_UGROUP_SYSTEM_ACCOUN FOREIGN KEY(UGROUP_ID) REFERENCES UGROUP (UGROUP_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
--- ワークアイテムの制約
ALTER TABLE TRANS_EXPE_APPLI_HISTORY
    ADD(CONSTRAINT FK_TRANS_EXPE_APPLICATION_TRAN FOREIGN KEY(TRANS_EXPE_APPLI_ID) REFERENCES TRANS_EXPE_APPLICATION (TRANS_EXPE_APPLI_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE LOAN_APPLICATION_HISTORY
    ADD(CONSTRAINT FK_LOAN_APPLICATION_WF_HISTORY FOREIGN KEY(LOAN_APPLI_ID) REFERENCES LOAN_APPLICATION (LOAN_APPLI_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
--- ワークフローインスタンスへのアサインに関する制約
ALTER TABLE WF_ACTIVE_GROUP_TASK
    ADD(CONSTRAINT FK_UGROUP_WF_ACTIVE_GROUP_TASK FOREIGN KEY(ASSIGNED_GROUP_ID) REFERENCES UGROUP (UGROUP_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_ACTIVE_USER_TASK
    ADD(CONSTRAINT FK_SYSTEM_ACCOUNT_WF_ACTIVE_US FOREIGN KEY(ASSIGNED_USER_ID) REFERENCES SYSTEM_ACCOUNT (USER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_TASK_ASSIGNED_GROUP
    ADD(CONSTRAINT FK_UGROUP_WF_TASK_ASSIGNED_GRO FOREIGN KEY(ASSIGNED_GROUP_ID) REFERENCES UGROUP (UGROUP_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_TASK_ASSIGNED_USER
    ADD(CONSTRAINT FK_SYSTEM_ACCOUNT_WF_TASK_ASSI FOREIGN KEY(ASSIGNED_USER_ID) REFERENCES SYSTEM_ACCOUNT (USER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
--- ワークフローエンジンでの制約
ALTER TABLE WF_ACTIVE_GROUP_TASK
    ADD(CONSTRAINT FK_WF_ACTIVE_NODE_GROUP_TASK FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_ACTIVE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_ACTIVE_USER_TASK
    ADD(CONSTRAINT FK_WF_ACTIVE_NODE_USER_TASK FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_ACTIVE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_TASK_ASSIGNED_GROUP
    ADD(CONSTRAINT FK_WF_INSTANCE_NODE_GROUP FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_TASK_ASSIGNED_USER
    ADD(CONSTRAINT FK_WF_INSTANCE_NODE_USER FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_ACTIVE_FLOW_NODE
    ADD(CONSTRAINT FK_WF_INSTANCE_NODE_ACTIVE_NOD FOREIGN KEY(INSTANCE_ID, FLOW_NODE_ID) REFERENCES WF_INSTANCE_FLOW_NODE (INSTANCE_ID, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_INSTANCE_FLOW_NODE
    ADD(CONSTRAINT FK_WF_INSTANCE_FLOW_NODE FOREIGN KEY(INSTANCE_ID) REFERENCES WF_INSTANCE (INSTANCE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_INSTANCE
    ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_INSTANCE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_INSTANCE_FLOW_NODE
    ADD(CONSTRAINT FK_WF_FLOW_NODE_INSTANCE_NODE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_LANE
    ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_LANE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_FLOW_NODE
    ADD(CONSTRAINT FK_WF_LANE_FLOW_NODE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, LANE_ID) REFERENCES WF_LANE (WORKFLOW_ID, DEF_VERSION, LANE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_BOUNDARY_EVENT_TRIGGER
    ADD(CONSTRAINT FK_WF_WORKFLOW_DEF_TRIGGER FOREIGN KEY(WORKFLOW_ID, DEF_VERSION) REFERENCES WF_WORKFLOW_DEFINITION (WORKFLOW_ID, DEF_VERSION) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_BOUNDARY_EVENT
    ADD(CONSTRAINT FK_WF_TRIGGER_BOUNDARY_EVENT FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, BOUNDARY_EVENT_TRIGGER_ID) REFERENCES WF_BOUNDARY_EVENT_TRIGGER (WORKFLOW_ID, DEF_VERSION, BOUNDARY_EVENT_TRIGGER_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_SEQUENCE_FLOW
    ADD(CONSTRAINT FK_WF_FLOW_NODE_SEQ_TARGET FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, TARGET_FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_SEQUENCE_FLOW
    ADD(CONSTRAINT FK_WF_FLOW_NODE_SEQ_SOURCE FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, SOURCE_FLOW_NODE_ID) REFERENCES WF_FLOW_NODE (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
ALTER TABLE WF_BOUNDARY_EVENT
    ADD(CONSTRAINT FK_WF_TASK_BOUNDARY_EVENT FOREIGN KEY(WORKFLOW_ID, DEF_VERSION, ATTACHED_TASK_ID) REFERENCES WF_TASK (WORKFLOW_ID, DEF_VERSION, FLOW_NODE_ID) DEFERRABLE INITIALLY IMMEDIATE)
;
